services:
  postgres:
    image: postgres:17.4-alpine
    container_name: nestjs_starter_postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER = ${POSTGRES_USER}
      - POSTGRES_PASSWORD = ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgressql/data
  redis:  
    image: redis:8.0-rc1-alpine
    container_name: nestjs_starter_redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

networks:
  default:
    name: nestjs

volumes:
  postgres_data:
  redis_data:

